### ISSUE TITLE
Class 'CHtml' not found

### ISSUE THREAD

**Issue by MVprobr** [WASasquatch/humhub-themes-thermalcore#1]
PHP Fatal Error – yii\base\ErrorException

Class 'CHtml' not found
1. in /home/casiufvcrp/casiufvcrp/site/themes/thermalcore/views/layouts/main.php at line 7
12345678910111213141516<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html lang="en">
<head>
    
    <meta charset="utf-8">
    <title><?php echo CHtml::encode($this->pageTitle); ?></title>
    
 
    
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
 
    <?php $ver = HVersion::VERSION; ?>
 
    
2. yii\base\ErrorHandler::handleFatalError()

**Comment by WASasquatch** [comment]
I'm sorry but ThermalCore is not updated to any current versions of HumHub, and I have stopped development with HumHub framework.
